### ISSUE TITLE
How to create the original training datasets

### ISSUE THREAD

**Issue by aoi-lab** [jinlinyi/PerspectiveFields#10]
Hello!
I'm interested in the method you proposed.
I would like to train using the original dataset.
What camera parameters are required to create the training data?
Specifically, I have the following camera parameters.
Can I create training data from these parameters?
If it's possible, please let me know how to create it.

> {
> 			"name": "01_01",
> 			"type": "vga",
> 			"resolution": [640,480],
> 			"panel": 1,
> 			"node": 1,
> 			"K": [
> 				[746.86,0,374.524],
> 				[0,746.925,225.938],
> 				[0,0,1]
> 			],
> 			"distCoef": [-0.340115,0.146277,-0.000603648,0.00102124,-0.0713998],
> 			"R": [
> 				[0.956838847,0.02823940406,-0.2892437672],
> 				[-0.05138652454,0.9960257947,-0.07274641811],
> 				[0.2860399376,0.08446983077,0.9544872979]
> 			],
> 			"t": [
> 				[-49.26603657],
> 				[143.452285],
> 				[280.6572141]
> 			]
> 		},

I look forward to hearing good news.

**Comment by jinlinyi** [comment]
Thank you for your interest in our project and for providing your example!

To create training data from these parameters, you can refer to this [notebook](https://github.com/jinlinyi/PerspectiveFields/blob/90afeb219575278845b0b9ea49c4b48c7020dd06/jupyter-notebooks/camera2perspective.ipynb) which demonstrates how to convert camera parameters to Perspective Fields. Currently, we support conversion from a pin-hole camera model (using roll, pitch, fov and principal point) or from a camera with distortion, assuming the Unified Spherical Model. If you prefer, you can also manually calculate the corresponding Up-vector and Latitude map by following Equations 1 and 2 in our paper. 

In your specific case, you can extract roll and pitch from "R" matrix (depending on how your coordinate frame is defined), and field of view and principal location from "K". However, your "distCoef" represents a distortion model that we currently do not support in our implementation. If you wish to account for this distortion, you would need to manually calculate the projection by following Eqn 1 and 2 in our paper. 

Please let me know if you have further questions or if there's anything else that I can assist with you.

**Comment by aoi-lab** [comment]
Thanks for your reply; it appears that we can proceed with constructing the dataset.

I have a few more questions.

1. What are the necessary ground truth data for training?
 In the [datasets/gsv_train_20210313.csv file](https://github.com/jinlinyi/PerspectiveFields/blob/main/datasets/gsv_train_20210313.csv),
> 00022342_63f493c2/gsvi_64_8_-17_512.jpg, 00022342_63f493c2/gsvi_64_8_-17_512_line.csv, 64.0, 8, -17, 512.1070492931361, -73.34425314111218, 286.8373168883925, 519.7776653494736, 441.99231930345263
 
 Are all of these data items required?
 Additionally, could you please provide an explanation for each item?

2. I am unable to generate (image_name)_line.csv with the dataset I'm currently working on. Can I still train PerspectiveNet?

Apologies for the multiple inquiries.
Thank you in advance.

**Comment by jinlinyi** [comment]
1. For the most common pinhole camera image, we did not use all the info provided in the original csv file. We just need roll, pitch, vfov. See the following dataloader for the detailed info. 
https://github.com/jinlinyi/PerspectiveFields/blob/b6235da73c2e028051b3ec994859b83ca9583b1c/perspective2d/data/datasets/gsv.py#L22-L29


2. If you don't have these parameters, you can still train it if you can calculate the ground truth Up-vector and Latitude and save them as hdf5 files. 
```python
import h5py
def write_hdf5(path, data):
    with h5py.File(path, "w") as f: 
        f.create_dataset("dataset", data=data.astype(np.float16), compression="gzip", compression_opts=9)

out_gfield_hdf5_file      = os.path.join(save_f, 'label', basename+"_gravity.hdf5")
out_lati_hdf5_file      = os.path.join(save_f, 'label', basename+"_latitude.hdf5")
write_hdf5(out_gfield_hdf5_file, gt_up_vector)
write_hdf5(out_lati_hdf5_file, gt_latitude)
``` 
And then, you can create a json file like [this](https://github.com/jinlinyi/PerspectiveFields/blob/main/datasets/gsv_test_crop_uniform.json). 

In the dataloader, we provide functions to load them
https://github.com/jinlinyi/PerspectiveFields/blob/b6235da73c2e028051b3ec994859b83ca9583b1c/perspective2d/data/latitude_transform.py#L77

One small detail for Up-vector: 
- If you don't have distortion in the original image, it is recommended to calculate `vvp_abs` instead of directly using the full Up-vector map. We treat `vvp_abs` as `keypoint` during data augmentation, which is robust to random aspect ratio resizing. 
https://github.com/jinlinyi/PerspectiveFields/blob/b6235da73c2e028051b3ec994859b83ca9583b1c/perspective2d/data/gravity_transform.py#L83-L96

- If you DO have distortion in your data, our code supports reading the full Up-vector map, but you have to use `cfg.DATALOADER.AUGMENTATION_FUN = "with_up_field"` which uses fixed aspect ratio data augmentation.

https://github.com/jinlinyi/PerspectiveFields/blob/b6235da73c2e028051b3ec994859b83ca9583b1c/perspective2d/data/perspective_transforms.py#L275-L279

https://github.com/jinlinyi/PerspectiveFields/blob/b6235da73c2e028051b3ec994859b83ca9583b1c/perspective2d/data/gravity_transform.py#L119-L123

Thank you again for your interest in our project. Your feedback is very important for us to keep improving our documentation. So don't hesitate to ask questions if you do see anything confusing.

**Comment by aoi-lab** [comment]
I understand perfectly.
Thanks to your exceptional support, the training of PerspectiveNet has been progressing smoothly.

One report, when I first ran train.py,

> AttributeError: module 'distutils' has no attribute 'version'

error occurred.
this is,
`conda install -c conda-forge setuptools==59.5.0`
I solved it by running
This problem may be due to the fact that I installed from a different channel during setup, or it may be a problem specific to my environment.
If this is a problem specific to my environment, I apologize.

I will report back if I find any more problems.
Thank you so much for your assistance!

**Comment by aoi-lab** [comment]
We will reopen the issue.
I have a question regarding training ParamNet.
You previously provided information on the required data for training, but I would like to inquire specifically about the necessary data for training ParamNet.

I am trying to create a json file in the form of [edina_test_crop_vfov.json](https://github.com/jinlinyi/PerspectiveFields/blob/main/datasets/edina_test_crop_vfov.json),
> {"file_name": "scene0015_00/color/color_000000.png", "corners": [[-134, -54], [506, -54], [-134, 426], [506, 426]], "latitude_file_name": "scene0015_00/label/scene0015_00_color_color_000000_latitude.hdf5", "gt_latitude_original_mode": "deg", "gravity_file_name": "scene0015_00/label/scene0015_00_color_color_000000_gravity.hdf5", "vvp_abs": [201.88505339031883, 623.387884521999, -1.0], "center": [186.0, 186.0], "horizon": [[-134.0, -212.963320757727], [506.0, -236.91108122442984]], "seed": 0, "focal_length": 424.19856389829386, "vfov": 47.35239367380666, "roll": 2.1429152552234254, "pitch": -44.07022906805002, "height": 372, "width": 372, "dataset": "edina_crop"}

Could you please specify the required information for the mentioned items?
Additionally, could you explain the meaning of "vvp_abs"?

Furthermore, for the testing phase, I intend to utilize data that does not require any cropping.
I understand that "corners" represents the coordinates of the four points to be cropped, but is it an optional field?

**Comment by jinlinyi** [comment]
Hi, thanks for the good questions.

For training, you should follow [edina_train.json ](https://raw.githubusercontent.com/jinlinyi/PerspectiveFields/main/datasets/edina_train.json)
Only `{"file_name": "scene0000_00/color/color_000010.png", "height": 480, "width": 640, "roll": 3.361576753044205, "pitch": -34.98233965075324, "vfov": 59.0}` is required.

`horizon` and `corners` are redundant information and are not used during either training or testing. 

`vvp_abs` is the absolute vertical vanishing point in the image frame (top left corner as 0), see the below code block.
https://github.com/jinlinyi/PerspectiveFields/blob/b6235da73c2e028051b3ec994859b83ca9583b1c/perspective2d/utils/panocam.py#L285C1-L309
and this issue
https://github.com/jinlinyi/PerspectiveFields/issues/4#issuecomment-1553264429

**Comment by aoi-lab** [comment]
thank you. Problem solved!

I have several detailed questions.

1. What is the difference between estimating or not estimating the training principal points of ParamNet? What are some things you can't do without inferring the principal point?
2. I would like to ask about the hardware environment for the experiment. (especially how many of which kind of GPU you used)

Thank you for always helping me.

**Comment by jinlinyi** [comment]
- Principal point is part of the intrinsic. It tells you the camera's optical axis of an image. It is useful in geometric correction (e.g. fix radial distortion etc) and 3D reconstruction (e.g. calculate point cloud / surface normal from depth image). Please refer to our [paper](https://arxiv.org/pdf/2212.03239.pdf) for details (checkout our teaser image). 

- We used two NVIDIA A40 for training.

**Comment by aoi-lab** [comment]
It was a good reference.
thank you!
